In [2]:
!pip install numpy

In [3]:
import numpy

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(np.__version__)

1.19.2


In [6]:
import numpy as np
arr = np.array(12)

print(arr)
print(type(arr))
print(arr.ndim)

12
<class 'numpy.ndarray'>
0


In [7]:
import numpy as np
arr = np.array([[1,2,3,4,5],[7,8,9,5,4],[3,7,4,9,7]])

print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0:3,0:4])

[[1 2 3 4 5]
 [7 8 9 5 4]
 [3 7 4 9 7]]
<class 'numpy.ndarray'>
2
[[1 2 3 4]
 [7 8 9 5]
 [3 7 4 9]]


In [8]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,9,6,8,3]],[[1,2,3,4,5],[7,2,9,5,7]]])

print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4 5]
  [6 9 6 8 3]]

 [[1 2 3 4 5]
  [7 2 9 5 7]]]
<class 'numpy.ndarray'>
3


In [9]:
# input for user

n = int(input("enter size"))

list = []
for i in range(0,n):
    num = int(input("enter value : "))
    list.append(num)
    
print(list)
arr = np.array(list)
print(arr)

enter size6
enter value : 1
enter value : 2
enter value : 3
enter value : 4
enter value : 5
enter value : 6
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [10]:
# SLICING OF 1-d ARRAY
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0:2])

[1 2]


In [11]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,3],[4,6,9,2,5],[3,5,1,9,7]])
print(arr[0:3,1:3])

[[2 3]
 [7 8]
 [6 9]]


In [12]:
import numpy as np
arr = np.array([1,2,3,4,5])
b = arr + 5
print(b)

[ 6  7  8  9 10]


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,9,4,8,7])
#c = arr + arr2
c = arr * arr2
print(c)

[ 6 18 12 32 35]


# DOT PRODUCT AND CROSS PRODUCT

In [14]:
arr = np.array([1,2,3])
arr2 = np.array([6,9,4])
print(np.dot(arr,arr2))
print(np.cross(arr,arr2))

36
[-19  14  -3]


In [15]:
a = np.array([1,2,3,4,5])
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [16]:
a = np.array([np.pi,np.pi/2,np.pi/3,np.pi/4])
print(np.cos(a))
print(np.sin(a))

[-1.00000000e+00  6.12323400e-17  5.00000000e-01  7.07106781e-01]
[1.22464680e-16 1.00000000e+00 8.66025404e-01 7.07106781e-01]


In [17]:
arr = np.arange(2,20,2)   #(start,stop,increment)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


In [18]:
arr = np.linspace(2,10,8) #(start,stop,no. of elements)
print(arr)

[ 2.          3.14285714  4.28571429  5.42857143  6.57142857  7.71428571
  8.85714286 10.        ]


In [19]:
arr = np.logspace(3,4,8)  #(10^first, 10^middle, no. of  elements)
print(arr)

[ 1000.          1389.49549437  1930.69772888  2682.69579528
  3727.59372031  5179.47467923  7196.85673001 10000.        ]


In [20]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# ANOTHER DECLARATION OF ARRAY USING DATATYPE
arr = np.array([2,5,4,1], dtype = 'int64')
#arr = np.array([2,5,'fd',1], dtype = 'int64') error
print(arr)

[2 5 4 1]


In [22]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [23]:
arr = np.random.randint(0,15,8)   #(start,stop,number of elements)
print(arr)

[8 6 4 5 1 6 1 5]


In [24]:
arr = np.random.rand(5) # for float values random array
print(arr)

[0.55519243 0.44570223 0.45236469 0.25989986 0.10572463]


In [25]:
arr = np.random.rand(9)*10
print(arr)

[2.75325011 4.41842547 0.77710974 8.6236261  7.08336079 4.11955598
 7.83397008 2.41882328 9.88879349]


In [26]:
arr = np.random.rand(2,5,5)*3 +5
              #(no.of matrix,row,column)* upto + fromwhere
print(arr)

[[[7.92911741 7.44698356 5.61428105 6.55827717 5.16706854]
  [7.16340502 6.96608487 7.61068984 5.71283505 7.47546026]
  [5.49057247 6.06722722 7.94181476 7.42243752 7.52417038]
  [7.78166849 6.48376139 7.76523882 6.11422215 6.30642584]
  [5.96080794 6.28072539 7.41542748 6.19653367 6.06545834]]

 [[6.04835081 7.5191792  7.312555   5.3198689  5.84127513]
  [6.08585888 7.8034456  7.08701407 6.82923474 6.93425825]
  [6.55608161 6.54799367 7.51138207 6.95234437 6.84315556]
  [5.25177647 5.56241203 5.57817865 7.56871782 7.06456068]
  [7.32110412 7.53563329 7.65566337 7.17417443 7.32674611]]]


In [27]:
list = [3,5,9,3,8,2,7]
arr = np.random.choice(list,5) # to take random from list
print(arr)

[8 3 8 8 2]


In [28]:
# to check whether any of element in a given isa non zero
import numpy as np
arr = np.array([0,5,0,0,3])
for i in arr:
    if i!=0:
        print("Yes")
        break
        


Yes


In [41]:
arr = np.array([1,1,0,1,1])
print(np.all(arr)) # to check all are 1 in arr
print(np.any(arr)) # to check if a num>0 is present

False
True


In [30]:
arr = np.arange(30,72,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [31]:
arr = np.random.rand(5)*1 + 0
print(arr)

[0.78131839 0.8009469  0.39161356 0.13089372 0.27498092]


In [32]:
arr = np.array([10,10,20,20,30,30])
print("ORIGINAL ARRAY: ",arr)
arr2 = np.unique(arr)
print("UNIQUE ARRAY: ",arr2)


ORIGINAL ARRAY:  [10 10 20 20 30 30]
UNIQUE ARRAY:  [10 20 30]


In [67]:
# input of 2-d array
import numpy as np
lis = []
row = int(input("enter rows : "))
for i in range(row):
    for j in [input().split()]:
        lis.append(j)
        arr = np.array(lis,dtype=int)
        
print(arr)

enter rows : 3
1 2 3
1 22 3
5 6 7
[[ 1  2  3]
 [ 1 22  3]
 [ 5  6  7]]


In [ ]:
## NUMBER IS PERFECT OR NOT
def perfect(num):
    sum = 0
    for i in range(1,num):
        if(num%i==0):
            sum = sum + i;
    if(sum==num):
        print("PERFECT")
    else:
        print("NOT PERFECT")

n = int(input("ENTER NO."))
perfect(n)

In [ ]:
#PERFECT NUMBER BETWEEN RANGE
def perfect():
    sum = 0
    for i in range(1,1000):
        sum = 0
        num = i
        for j in range(1,num):
            if(num%j==0):
                sum = sum + j
        if(sum==i):
            print("PERFECT NO. IS : ",i)

perfect()


In [37]:
# N FIBONACCI NUMBER

def fibo(n):
    if(n<=1):
        return n;
    else:
        return (fibo(n-1) + fibo(n-2))
    
    
num = int(input("ENTER NUMBER: "))
#list = []
for i in range(0,num):
    #list.append(fibo(i))
    print(fibo(i))

ENTER NUMBER: 10
0
1
1
2
3
5
8
13
21
34


In [39]:
# ALTERNATE OF ABOVE
def fiboseries(num):
    a=0
    b=1
    for i in range(num):
        print(a)
        temp = a
        a = b
        b = temp + b
        
num = int(input("ENTER NUM : "))
fiboseries(num)

ENTER NUM : 10
0
1
1
2
3
5
8
13
21
34


In [60]:
# A PASSWORD GENERATOR IN PYHTON
