In [3]:
import numpy as np

In [4]:
#1 D Array
a = np.array([1,2,3])

In [5]:
a.shape

(3,)

In [6]:
b = np.array([(1,2,3),(4,5,6)])

In [7]:
b.shape

(2, 3)

In [8]:
c = np.random.rand(8,8)

In [9]:
c.shape

(8, 8)

In [10]:
c.size

64

In [11]:
d = c.reshape(64,)

In [12]:
print(d.shape)
print(d)

(64,)
[0.02268231 0.99792099 0.83632513 0.94005678 0.99962486 0.04600214
 0.34702112 0.32352812 0.71320845 0.69085951 0.65253016 0.37958146
 0.72435398 0.60201505 0.12803124 0.96297766 0.58587986 0.66831576
 0.97012806 0.46045693 0.69545525 0.16462114 0.64713258 0.17654163
 0.65614145 0.90078507 0.57818096 0.87235977 0.58173253 0.86965467
 0.48605864 0.63048761 0.74948606 0.50650179 0.94732962 0.23055817
 0.5836291  0.26127631 0.96798729 0.54333677 0.56068582 0.76105178
 0.95015783 0.02192344 0.63522056 0.12072607 0.74991541 0.51975596
 0.92603321 0.16149865 0.63543715 0.8636716  0.24525939 0.67648451
 0.95648592 0.93454778 0.68626483 0.3951232  0.06687058 0.40499306
 0.65566624 0.56007582 0.85519098 0.52515403]


In [13]:
d.dtype

dtype('float64')

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.randn(8,8)

array([[-0.94375965,  1.34545998,  0.32308785, -0.10559757, -0.82242511,
        -0.80245724, -0.80448697, -2.78421775],
       [ 0.47380469, -0.51276845, -0.18125036, -0.93897431,  0.09196808,
        -1.08863736,  1.31427334, -0.25116522],
       [ 0.04296234, -1.59468755,  0.36398704, -1.26525272,  0.55252458,
         0.89048669, -1.84020323,  0.11697191],
       [-1.8414854 , -0.33194033, -0.43598919,  2.14514965, -1.6107334 ,
        -1.63306468,  0.33831573,  0.52927383],
       [ 2.16398241,  1.5786177 ,  0.70283967, -0.28946164, -0.89190784,
         0.45942845, -0.44070012,  0.76881101],
       [-0.81818912, -0.67792867, -1.20436752, -0.78688286, -1.10583928,
         1.41570499, -1.21373139,  1.69638441],
       [ 0.20408371, -0.13724645,  0.97022015,  1.7488385 ,  0.46221227,
         1.70244977,  2.01773135, -0.49812944],
       [-1.53056463, -0.968402  ,  0.1977191 ,  0.71588181,  0.51226743,
         0.3492862 ,  0.25930209, -0.63321502]])

In [45]:
e = np.random.randint(40, size=(4,4))

In [46]:
e

array([[16,  8, 39, 27],
       [37, 22, 23, 22],
       [35, 27,  9, 12],
       [10,  8, 34, 35]])

In [47]:
e.shape

(4, 4)

In [50]:
f = e.reshape(16)

In [51]:
f.shape

(16,)

In [52]:
e.T  #Transpose of the matrix

array([[16, 37, 35, 10],
       [ 8, 22, 27,  8],
       [39, 23,  9, 34],
       [27, 22, 12, 35]])

In [55]:
f = f.reshape(2,2,4)

In [56]:
f.shape

(2, 2, 4)

In [57]:
f

array([[[16,  8, 39, 27],
        [37, 22, 23, 22]],

       [[35, 27,  9, 12],
        [10,  8, 34, 35]]])

In [58]:
g = np.random.randint(16, size=(8,8))

In [59]:
g.shape
print(g)

[[14  7  8  4  6  5  1 13]
 [ 9  7  2  8 14  3 12 15]
 [10  4  5  6  1  3 10 12]
 [ 3 13  2 14  4 10  3  5]
 [ 1 12  2  0  0 14  0  3]
 [ 2  1 11  2  6  5  7  5]
 [ 2 14 10  2  4  6  2  4]
 [12  3  0  0  9  6 13  8]]


In [60]:
g.resize(4,4)

In [61]:
g.shape

(4, 4)

In [62]:
g

array([[14,  7,  8,  4],
       [ 6,  5,  1, 13],
       [ 9,  7,  2,  8],
       [14,  3, 12, 15]])

In [63]:
g[3]

array([14,  3, 12, 15])

In [64]:
g[3,2] = 30

In [65]:
g

array([[14,  7,  8,  4],
       [ 6,  5,  1, 13],
       [ 9,  7,  2,  8],
       [14,  3, 30, 15]])

In [66]:
g[1:3,3]

array([13,  8])

In [67]:
e.shape

(4, 4)

In [68]:
#Scalar Math
np.add(g,100)

array([[114, 107, 108, 104],
       [106, 105, 101, 113],
       [109, 107, 102, 108],
       [114, 103, 130, 115]])

In [69]:
np.subtract(g,100)

array([[-86, -93, -92, -96],
       [-94, -95, -99, -87],
       [-91, -93, -98, -92],
       [-86, -97, -70, -85]])

In [70]:
np.multiply(g,100)

array([[1400,  700,  800,  400],
       [ 600,  500,  100, 1300],
       [ 900,  700,  200,  800],
       [1400,  300, 3000, 1500]])

In [71]:
np.power(g,2)

array([[196,  49,  64,  16],
       [ 36,  25,   1, 169],
       [ 81,  49,   4,  64],
       [196,   9, 900, 225]], dtype=int32)

In [72]:
#Vector Math
np.add(g,e)

array([[30, 15, 47, 31],
       [43, 27, 24, 35],
       [44, 34, 11, 20],
       [24, 11, 64, 50]])

In [73]:
np.multiply(g,e)

array([[ 224,   56,  312,  108],
       [ 222,  110,   23,  286],
       [ 315,  189,   18,   96],
       [ 140,   24, 1020,  525]])

In [74]:
np.divide(g,e)

array([[0.875     , 0.875     , 0.20512821, 0.14814815],
       [0.16216216, 0.22727273, 0.04347826, 0.59090909],
       [0.25714286, 0.25925926, 0.22222222, 0.66666667],
       [1.4       , 0.375     , 0.88235294, 0.42857143]])

In [75]:
np.mean(g, axis=0)

array([10.75,  5.5 , 10.25, 10.  ])

In [76]:
np.mean(g)

9.125

In [77]:
np.mean(g,axis=1)

array([ 8.25,  6.25,  6.5 , 15.5 ])

In [78]:
g.max(axis=0)

array([14,  7, 30, 15])

In [79]:
g.max(axis=1)

array([14, 13,  9, 30])

In [80]:
g.max()

30

In [76]:
g.sum()

539

In [81]:
g.sum(axis=0)

array([43, 22, 41, 40])